### ISSUE TITLE
Adding subreddits to custom subreddit bar doesn't work (anymore)

### ISSUE THREAD

**Issue by vordenken** [bermudalocket/redditweaks#11]
I started using your tweak with version 1.6 . This is the version I also added 1 sub to the custom subreddit bar.
After upgrading to 1.6.1 I cannot add more subs. 
Heres a screenshot of what it looks like:
<img width="292" alt="Bildschirmfoto 2020-10-29 um 11 39 52" src="https://user-images.githubusercontent.com/62395860/97557789-8a138780-19db-11eb-936f-4c57d1cee266.png">

Other than that I love your extension, keep up the great work dude!

**Comment by bermudalocket** [comment]
Fixed in https://github.com/bermudalocket/redditweaks/releases/tag/1.6.2
