### ISSUE TITLE
Custom Subreddit Bar freezing while typing

### ISSUE THREAD

**Issue by Pinatata** [bermudalocket/redditweaks#12]
<img width="276" alt="Screen Shot 2021-02-10 at 10 45 59 PM" src="https://user-images.githubusercontent.com/22414023/107600423-c0bf8780-6bf1-11eb-9096-49fcbc27aac6.png">

Hi, I can't seem to add anything to the Custom Subreddit Bar. Immediately after starting to type the 'add' button turns into the spinning circle icon and stays suspended. Ultimately nothing is added and the 'add' button never returns.

**Comment by Pinatata** [comment]
Forgot to mention: Safari v14.0.3 (16610.4.3.1.4) / MacBook Air (M1, 2020) / MacOS Big Sur v11.2

**Comment by bermudalocket** [comment]
Fixed in https://github.com/bermudalocket/redditweaks/releases/tag/1.6.2
