### ISSUE TITLE
Custom subreddit bar enhancements

### ISSUE THREAD

**Issue by Pinatata** [bermudalocket/redditweaks#13]
The custom subreddit bar delivers as intended but set-up/management could be improved. Two improvements that I think would be impactful are:
1. Ability to re-order subreddit list after being added
2. Ability to add custom display names for subreddits on the subreddit bar (i.e. allowing the user to display 'WSB' on the subreddit bar instead of 'WallStreetBets')

**Comment by bermudalocket** [comment]
Awesome ideas! I'll aim to implement these in the next release.

**Comment by bermudalocket** [comment]
https://github.com/bermudalocket/redditweaks/releases/tag/1.6.4

**Comment by Pinatata** [comment]
These new features are perfect! Thank you so much for writing these so fast!
