### ISSUE TITLE
“redditweaks” is damaged and can’t be opened. You should move it to the Trash.

### ISSUE THREAD

**Issue by AndroidKitKat** [bermudalocket/redditweaks#2]
Tried downloading the latest release and am seeing this issue. Running macOS 10.15.2. 

[Here's what I'm seeing on my MacBook](https://waifupaste.moe/raw/cWr.png)

**Comment by bermudalocket** [comment]
@AndroidKitKat sorry about that! Can you give 1.2.1 a shot?

PS -- team purple accent color! :)

**Comment by AndroidKitKat** [comment]
Works great! Thanks for your work on this!
