### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by DifferentComputers** [bermudalocket/redditweaks#3]
The readme contains no info at all about how to install this. Almost looks like it has to be compiled before installation.

How do I install it?

**Comment by bermudalocket** [comment]
Download the latest release from the [releases page](https://github.com/bermudalocket/redditweaks/releases). Unzip the archive and drag-and-drop the app into `/Applications`. Run the app, and then enable the extension in Safari. You can then close the app as all of the functionality is handled in the Safari extension.

**Comment by DifferentComputers** [comment]
In the download folder redditweaks-master there are 24 files or folders. None of them are a drag and drop app.
![Screen Shot 2020-05-19 at 9 26 57 AM](https://user-images.githubusercontent.com/36273978/82332033-e4cba080-99b2-11ea-8005-ac1f17ecaa51.png)

**Comment by DifferentComputers** [comment]
Hmmm. I did not intentionally close this issue.

**Comment by DifferentComputers** [comment]
Apparently at the main page I downloaded the source, not the archive. It's running now.
