### ISSUE TITLE
[1.4] Dark Mode

### ISSUE THREAD

**Issue by mattieice2020** [bermudalocket/redditweaks#5]
When the application is first opened, the font does not adapt correctly to dark mode, rendering all text invisible against the window (10.15.6)

<img width="354" alt="Screen Shot 2020-07-20 at 12 00 51 PM" src="https://user-images.githubusercontent.com/66804731/87959296-ab7de280-ca80-11ea-85d3-d4122ba585a0.png">

**Comment by bermudalocket** [comment]
Version 1.4.1 has been published.

https://github.com/bermudalocket/redditweaks/releases/tag/1.4.1

**Comment by mattieice2020** [comment]
Re-opening: In 1.4.1b, the font in the custom subreddit text field is black even in dark mode (this may have been an issue all along but could not test due to issue #8 

<img width="297" alt="Screen Shot 2020-07-24 at 1 41 03 PM" src="https://user-images.githubusercontent.com/66804731/88419855-ddaa7f80-cdb3-11ea-965d-7ac02b1c9aaf.png">
