### ISSUE TITLE
[1.4.1] Extension Crashes, Does Not Open in Safari

### ISSUE THREAD

**Issue by mattieice2020** [bermudalocket/redditweaks#8]
Updated to 1.4.1 today; when opening the extension, the "Open In Safari" button does not open Safari or open the extensions preference pane if Safari is already open. In addition, clicking the icon in the toolbar seems to do nothing, but actually crashes the app according to the system console (Crash report attached below). Have tried a clean install by deleting the old version and all system files with AppCleaner but the issue persists (macOS 10.15.6, MacBook Pro 2015)

[Redditweaks Crash Report.txt](https://github.com/bermudalocket/redditweaks/files/4969066/Redditweaks.Crash.Report.txt)

**Comment by bermudalocket** [comment]
Apparently there is a bug with `#if available` in Swift(UI) that causes SwiftUI 2 features, like `LazyVStack`, to crash on iOS 13/macOS 10.15. Apple developers currently recommend wrapping SwiftUI 2-exclusive views in an `AnyView`. I'll try that now and will push a beta build.

**Comment by mattieice2020** [comment]
Fixed in 1.4.1b beta, although it took a restart of Safari to activate correctly (this may just be an issue with Safari, as the icon would appear and immediately disappear when activated. Restarting Safari and re-enabling the extension did fix this issue.

**Comment by bermudalocket** [comment]
Yeah, this is a really annoying Safari bug. It's been an issue since last June when the macOS Catalina beta was released. I will keep my eyes open for workarounds but for right now it seems like this is strictly Safari-side behavior.
