### ISSUE TITLE
[1.4.1b] Window Length (Custom Subreddit Bar)

### ISSUE THREAD

**Issue by mattieice2020** [bermudalocket/redditweaks#9]
Extension size does not adapt or allow scrolling if the custom subreddit bar gets too long (Any items that would be placed below r/swiftui are inaccessible)

<img width="311" alt="Screen Shot 2020-07-24 at 1 48 32 PM" src="https://user-images.githubusercontent.com/66804731/88420174-77722c80-cdb4-11ea-8a86-ca9c3551fc53.png">

**Comment by bermudalocket** [comment]
You should be able to scroll vertically: the extension view itself is embedded in a `ScrollView`.

Just want to clarify that you can't scroll vertically?

**Comment by mattieice2020** [comment]
Attached is a screen capture of the issue - I'm attempting to scroll in both directions, but only scrolling up gives any response (using a trackpad, if this helps, macOS 10.15.6). Also tried disabling other extensions to make sure it wasn't some conflict, although I didn't think that would have caused that.

![bugReport](https://user-images.githubusercontent.com/66804731/88446129-7f9e8c00-cdf5-11ea-987c-9842b7f62baf.gif)

**Comment by bermudalocket** [comment]
This should be fixed in 1.5 as I reworked the custom subreddit bar section.
